language: android
android:
  components:
      # The BuildTools version used by your project
      - build-tools-22.0.1
      # The SDK version used to compile your project
      - android-22
      # Additional components
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-android-m2repository
      - extra-android-support
      - extra-google-m2repository

branches:
  only:
    - develop

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew build
